config/routes.rb
Rails.application.routes.draw do
  resources :available_coaches
  resources :schedules
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available_coach.rb
class AvailableCoach < ApplicationRecord
  belongs_to :schedule
  require 'csv'
  
  NOMBRE_ARCHIVO = "AvailableTime.csv"

  class Choach
    attr_reader :name, :day_of_week, :available_at, :available_until

     def initialize(name, day_of_week, available_at, available_until )
      @name = name
      @day_of_week = day_of_week
      @available_at = available_at
      @available_until = available_until
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :name_user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/available_coaches_controller.rb
class AvailableCoachesController < ApplicationController
  before_action :set_available_coach, only: %i[ show edit update destroy ]
  
  # GET /available_coaches or /available_coaches.json
  def index
    @available_coaches = AvailableCoach.all
  end

  # GET /available_coaches/1 or /available_coaches/1.json
  def show
  end

  # GET /available_coaches/new
  def new
    @available_coach = AvailableCoach.new
  end

  # GET /available_coaches/1/edit
  def edit
  end

  # POST /available_coaches or /available_coaches.json
  def create
    @available_coach = AvailableCoach.new(available_coach_params)

    respond_to do |format|
      if @available_coach.save
        format.html { redirect_to available_coach_url(@available_coach), notice: "Available coach was successfully created." }
        format.json { render :show, status: :created, location: @available_coach }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @available_coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /available_coaches/1 or /available_coaches/1.json
  def update
    respond_to do |format|
      if @available_coach.update(available_coach_params)
        format.html { redirect_to available_coach_url(@available_coach), notice: "Available coach was successfully updated." }
        format.json { render :show, status: :ok, location: @available_coach }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @available_coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /available_coaches/1 or /available_coaches/1.json
  def destroy
    @available_coach.destroy

    respond_to do |format|
      format.html { redirect_to available_coaches_url, notice: "Available coach was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_available_coach
      @available_coach = AvailableCoach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def available_coach_params
      params.require(:available_coach).permit(:name, :day_of_week, :available_at, :available_until, :schedule_id)
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[ show edit update destroy ]

  # GET /schedules or /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1 or /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully created." }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: "Schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "Schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def schedule_params
      params.require(:schedule).permit(:name_user, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/available_coaches_helper.rb
module AvailableCoachesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/available_coaches/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@available_coach) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :day_of_week
    = f.input :available_at
    = f.input :available_until
    = f.association :schedule

  .form-actions
    = f.button :submit

app/views/available_coaches/edit.html.haml
%h1 Editing available_coach

= render 'form'

= link_to 'Show', @available_coach
\|
= link_to 'Back', available_coaches_path

app/views/available_coaches/index.html.haml
%h1 Available_coaches

%table
  %thead


  %tbody
    - @available_coaches.each do |available_coach|
      %tr
        %td= available_coach.name
        %td= available_coach.day_of_week
        %td= available_coach.available_at
        %td= available_coach.available_until
        %td= available_coach.schedule
        %td= link_to 'Show', available_coach
        %td= link_to 'Edit', edit_available_coach_path(available_coach)
        %td= link_to 'Destroy', available_coach, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Whatch Available coach', new_available_coach_path
= link_to 'Back', schedules_path

app/views/available_coaches/new.html.haml
%h1 Available_coach

= link_to 'Cristina Aguilera'
%br
= link_to 'Natalia Lafourcade'
%br
= link_to 'Shakira'
%br
= link_to 'Paulina Rubio'
%br
= link_to 'Alejandra Guzmán'
%br
%br

= link_to 'Back', available_coaches_path

app/views/available_coaches/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @available_coach.name
%p
  %b Day of week:
  = @available_coach.day_of_week
%p
  %b Available at:
  = @available_coach.available_at
%p
  %b Available until:
  = @available_coach.available_until
%p
  %b Schedule:
  = @available_coach.schedule

= link_to 'Edit', edit_available_coach_path(@available_coach)
\|
= link_to 'Back', available_coaches_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArAppointmentScheduler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.haml
= form_for @schedule do |f|
  - if @schedule.errors.any?
    #error_explanation
      %h2= "#{pluralize(@schedule.errors.count, "error")} prohibited this schedule from being saved:"
      %ul
        - @schedule.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name_user
    = f.text_field :name_user
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/schedules/edit.html.haml
%h1 Editing schedule

= render 'form'

= link_to 'Show', @schedule
\|
= link_to 'Back', schedules_path

app/views/schedules/index.html.haml
%h1 Listing schedules

%table
  %thead
    %tr
      %th Name user
      %th Description
      %th
      %th
      %th

  %tbody
    - @schedules.each do |schedule|
      %tr
        %td= schedule.name_user
        %td= schedule.description
        %td= link_to 'Show', schedule
        %td= link_to 'Edit', edit_schedule_path(schedule)
        %td= link_to 'Destroy', schedule, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Schedule', new_schedule_path

app/views/schedules/new.html.haml
%h1 New schedule

= render 'form'

= link_to 'Back', schedules_path

app/views/schedules/show.html.haml
%p#notice= notice

%p
  %b Name user:
  = @schedule.name_user
%p
  %b Description:
  = @schedule.description

= link_to 'Whatch Available coach', new_available_coach_path
%p
= link_to 'Edit', edit_schedule_path(@schedule)
\|
= link_to 'Back', schedules_path